feature/#13/application_파일_작성
kodesalon/HamKke pull request #14
Opened 2022-10-25 09:47 UTC by ch0ijihwan

## 개요
- #13 
- application.yml 파일 생성 및 기본적인 설정 정보 작성

## 작업사항
-  datasource 관련 설정 정보 기입
- jpa 설정 정보 기입
 

## 변경로직(optional)
- 없음

2022-10-29 09:00 UTC, seongbeenkim requested changes
지금 작성해주신 application.yml 파일은 프로젝트를 단순히 동작시키기 위한 파일 같이 보여요~ 

다시 한 번 어떻게 작성하는지 찾아보고 수정하셨으면 좋겠습니다!

2022-10-29 14:13 UTC, ch0ijihwan commented on src/main/resources/application.yml
> +      ddl-auto: create
1. create 같은 경우 데이터베이스를 초기화 할 때, drop 후 create 를 한다고 알고 있습니다. 현재 단계에서는 아직 개발 초기라서 이렇게 해두는게 나을 것 같다고 생각했습니다. 지금 spring profile을 적용하려고 하는데, 이를 적용하면서 환경에 따라 auto-ddl 전략을 변경 하도록 하겠습니다.
2. 반영하도록 하겠습니다.
3. 데이터베이스에 따라서 방언이 있기 때문에 이를 지정해줘야 한다고 알고 있었습니다. 그런데 찾아보니,, Dialect 설정은 안하는게 좋다는 것을 알게되어습니다. -> 그 이유로는 스프링 부트가 자동으로 해주기 때문에 굳이 할 필요가 없다고 합니다.
 명시적으로 Dialect 설정을 하게 되는 경우, 실제 사용한 db와 버전이 다른 경우 예상치 못한 상황이 발생 할 수 있기 때문에 설정을 안하는게 좋다고 합니다.

2022-10-30 09:06 UTC, seongbeenkim commented on src/main/resources/application.yml
> +      ddl-auto: create
@ch0ijihwan 
위 질문드린 사항 외에도 mysql timezone, encoding 등 설정 및 spring profile 까지 다시 모두 적용하고 request 다시 요청 주시면 좋을 것 같아요~

2022-11-06 02:03 UTC, seongbeenkim approved these changes
환경분리 해주셨네요~ 
database: mysql 만 제거해주시면 될 것 같으니 Approve 하겠습니다~

2022-11-06 02:03 UTC, seongbeenkim commented on src/main/resources/application.yml
> +    database: mysql
빼셔도 될 것 같아요~

2022-11-06 05:46 UTC, ch0ijihwan commented on src/main/resources/application.yml
> +    database: mysql
변경 후 다시 푸시 하겠습니다!

2022-11-08 13:03 UTC, ch0ijihwan commented
디폴트 profile이 local 로 잡히도록 변경하였습니다. 
datasource 에서 url 설정 변경 하였습니다.

2022-11-09 12:19 UTC, seongbeenkim approved these changes
default profile 및 db 변경 잘해주신 것 같아요~

2022-11-09 12:19 UTC, seongbeenkim commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&character_set_server=utf8mb4&allowPublicKeyRetrieval=true
`character_set_server=utf8mb4` 굿굿~

[MySQL 공식 문서](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-troubleshooting.html)에 따르면 8.0.13 이상 버전일 경우 `characterEncoding=UTF-8` 를 해도 `utf8mb4` 로 작동한다고 합니다

15.11: How can I use 4-byte UTF8 (utf8mb4) with Connector/J?

- To use 4-byte UTF8 with Connector/J configure the MySQL server with [character_set_server=utf8mb4](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_server). Connector/J will then use that setting, if characterEncoding and connectionCollation have not been set in the connection string. This is equivalent to autodetection of the character set. See [Section 6.7, “Using Character Sets and Unicode”](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-charsets.html) for details. For 8.0.13 and later: You can use characterEncoding=UTF-8 to use utf8mb4, even if [character_set_server](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_server) on the server has been set to something else.

그리고 mysql 8.0.23 버전 이상 사용하시면 `serverTimezone` 대신 `connectionTimeZone` 사용해보는 것도 좋을 것 같아서 해당 내용도 공유드립니다. 안바꿔도 돼요! 다른 분들한테도 공유드리고자 남기는 글이에여~

`For Connector/J 8.0.23 and later, serverTimezone is an alias for connectionTimeZone. For Connector/J 8.0.22 and earlier, serverTimezone was used to override the session time zone setting on the server.`

`Former connection option 'serverTimezone' is still valid as an alias of this one but may be deprecated in the future.`

2022-11-10 10:52 UTC, ch0ijihwan commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&character_set_server=utf8mb4&allowPublicKeyRetrieval=true
블로그 내용으로만 확인해서 애매해서 확실하게 공식 문서를 보고 있었는데, 여기 까진 못 봤었네요..
감사합니다!

2022-11-10 10:52 UTC, merged