Feature/게시판 제약조건 구현
kodesalon/HamKke pull request #2
Opened 2022-10-12 07:49 UTC by ch0ijihwan

게시판 글에 쓰이는 [제목, 글내용]의 유효검사 및 값을 갖고 있는 객체를 구현 했습니다.

- Title 
   25자 이하, 공백 x

-Content
   -1000자 제한, 공백 x

2022-10-13 08:08 UTC, seongbeenkim submitted a review, later dismissed
이전 PR 코드와 차이가 없어서 저는 approve 하겠습니다~

2022-10-16 05:49 UTC, sdrs6921 requested changes
저도 이전 PR과 크게 다른 점이 없어서 몇 가지 코멘트만 남겼습니다.
추가로 PR 템플릿을 만들어서 만드는 것도 좋을 것 같습니다! 여러 가지 템플릿들을 확인해보며 활용해보는 것도 좋을 것 같아요!

2022-10-16 05:49 UTC, sdrs6921 commented on board/src/test/java/hamkke/board/model/user/PasswordTest.java
> +    @DisplayName("비밀번호는 영문(대문자,소문자), 특수문자(!,@,#,$,%,^,&,*,_,-), 숫자를 최소 1개 이상 조합한 8자 이상 18자 이하여야합니다.")
[이 코멘트](https://github.com/kodesalon/HamKke/pull/1/files#r996392208)와 동일한 내용이네요~

2022-10-16 05:49 UTC, sdrs6921 commented on board/src/main/java/hamkke/board/model/bulletin/Content.java
> +    public String getValue() {
[이 코멘트](https://github.com/kodesalon/HamKke/pull/1/files#r996392004)와 동일한 내용이네요~

2022-10-29 14:56 UTC, ch0ijihwan commented
Can one of the admins verify this patch?

2022-11-06 12:54 UTC, seonghun127 submitted a review, later dismissed
간단한 작업이라 approve 할게요~

2022-11-22 12:59 UTC, sdrs6921 approved these changes
저도 간단한 작업이라고 생각해서 한 가지 코멘트를 만 달고서 어프 드립니다~ 추가적으로 지금 현재 develop 브랜치와 충돌하는데, 어떠한 방식으로 충동을 해결할 것인지 고민해보는 것도 좋을 것 같아요~! 고생하셨습니다~

2022-11-22 12:59 UTC, sdrs6921 commented on src/test/java/hamkke/board/model/bulletin/ContentTest.java
> +    @DisplayName("글 내용은 최대 1000 자여야한다.")
여기도 이전 PR에 남긴 코멘트와 동일한데, `@DisplayName`과 메서드 명에 예외가 발생하는 테스트라는 점을 명시해주는 것이 좋을 것 같습니다~

2022-11-23 03:38 UTC, merged