Feature/#20/회원가입 기능 구현
kodesalon/HamKke pull request #22
Opened 2022-11-18 08:27 UTC by ch0ijihwan

###회원가입 기능 구현

##변경 사항 
- 회원 가입 로직을 위한 repository, controller, service 를 만들었습니다.
- 예외처리를 해주기 위해 exceptionHandler 를 이용하였습니다.
- 상황에 따라 값을 감쌀 수 있는 dto를 생성했습니다.
   
##그 외
- 유저의 회원 가입 정보를 받을 때, `null`이 들어오지 않도록 `@vaildated` 를 사용했습니다.  
- 구현을 함에 있어서 테스트 코드를 어떻게 짜야할지 고민을 많이 했습니다. 기존에 하던 테스트 방식으로는 한계가 느껴져서, mocking 을 이용해 테스트를 해보려고 노력했습니다. 하지만 아직 조금 어렵다는 생각이 듭니다. 테스트 범위를 어디서 부터 어디까지 해야할지, mock 설정을 어디까지 해야할지 고민이 많았습니다. 고민 시간 좀 오래걸려서 그래서 일단 할 수 있는데 까지 해보고, 피드백을 받고 수정하기로 했습니다.
- 현재는 단위테스트로 구현을 하기로 했고, 통합테스트도 짜볼 생각입니다.
---
질문 사항
- 현재 컨트롤러 테스트 코드에서 예외 상황에 따라서 HTTP 400 코드를 반환하는 로직이 있습니다. 테스트 코드를 구현하고 보니  `loginId` 가 중복되는 상황과, `Alias` 가 중복되는 상황의 테스트 코드가 같은 동작을 하고 있지 않나? 라는 생각이 들었습니다. 
저는 userService를 mock 객체로 만들었습니다.
 `loginId` 가 중복되는 상황과, `Alias` 가 중복되는 상황 모두  첫번째 회원 가입 요청 시 Long 타입 을 감싼 DTO를 반환하고, 두번째 요청(중복되는 값이 있는)시 예외가 터지도록 mocking을 하였습니다.  

일단 이런방식(mock 활용 방법)으로 단위 테스트를 하는게 맞는지 궁금합니다. 

- 그리고 테스트 관련해서 놓친부분이 있는지 궁금합니다!!

2022-11-18 12:23 UTC, seongbeenkim requested changes
> 현재 컨트롤러 테스트 코드에서 예외 상황에 따라서 HTTP 400 코드를 반환하는 로직이 있습니다. 테스트 코드를 구현하고 보니 loginId 가 중복되는 상황과, Alias 가 중복되는 상황의 테스트 코드가 같은 동작을 하고 있지 않나?

의도적으로 분리하신 예외 케이스이기 때문에, 테스트 코드가 중복이더라도 추가하는게 좋다고 생각해요~

> 일단 이런방식(mock 활용 방법)으로 단위 테스트를 하는게 맞는지 궁금합니다.

넵 controller 테스트 보니 mock 활용 잘해주신 것 같아요~

궁금한 부분 및 수정해야할 부분 코멘트 확인해주시면 될 것 같습니다~

2022-11-18 12:23 UTC, seongbeenkim commented on src/test/java/hamkke/board/service/UserServiceTest.java
>  @DataJpaTest
@Import(JpaAuditingConfiguration.class) 추가해줘야 하는 이유가 있을까요?

2022-11-18 12:23 UTC, seongbeenkim commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +                .content(objectMapper.writeValueAsString(existedUserRequest)));
제거해도 될 것 같아요~

2022-11-18 12:23 UTC, seongbeenkim commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +                .content(objectMapper.writeValueAsString(existedUserRequest)));
제거해도 될 것 같아요~

2022-11-18 12:23 UTC, seongbeenkim commented on src/main/java/hamkke/board/controller/UserController.java
> +    public ResponseEntity<UserResponse> join(@Validated @RequestBody final CreateUserRequest createUserRequest) {
@Valid가 아닌 @Validated를 사용하신 이유가 있나요??

2022-11-18 12:23 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/UserService.java
> +    private void validateLoginIdDuplication(final CreateUserRequest createUserRequest) {
함수 띄어쓰기 해주세용~

2022-11-18 13:10 UTC, ch0ijihwan commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok'
인텔리 상에서는 인덴트 문제가 없어 보였는데, 다시 정렬해보고 푸시하겠습니다.

2022-11-18 13:15 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
일단 처음에 구현했을 때, DTO 에는 `getter`, `setter` 만 있는거라고 생각해서 구현을 해줬었습니다. 하지만 구현 하면서 필요 없다고 생각이 들어서 `@setter`를 제거 해주었습니다.

2022-11-18 13:16 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
혹시 요청이 제대로 매핑이 된다는 의미가,  컨트롤러에서 요청을 받을 때, 해당 DTO로 body가 변환되서 요청이 들어오는 것인지에 대한 의미인가요?

2022-11-18 13:29 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
넵넵 실제 요청 보낼 시 제대로 맵핑이 되는지 궁금했어요

2022-11-18 13:32 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/UserService.java
> +    private void validateLoginIdDuplication(final CreateUserRequest createUserRequest) {
변경 하였습니다.

2022-11-18 13:35 UTC, ch0ijihwan commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +}
공부해보고, 테스트 코드 다시 작성해보겠습니다.

2022-11-18 13:56 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
앗 죄송해요 지금 작성해주신 컨트롤러 테스트 코드 작동하면 검증된 겁니다~

제가 Jackson 직렬화/역직렬화 부분 
getter/setter + NoArgumentConstructor 필수로 있어야만 매핑된다고 생각했는데,
getter/setter + AllArgumentConstructor 도 동작이 되는군요..
이 부분은 제가 더 찾아보고 공유하도록 하겠습니다~

2022-11-18 13:59 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
네 알겠습니다! 감사합니다!

2022-11-18 14:27 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
오호.. 찾아보니 
Spring Boot 2.x 버전대로 들어오면서 `ObjectMapper` 에 `jackson-module-parameter-names` 모듈이 포함되어 있어, 
기본생성자가 존재하지 않아도 인자가 있는 다른 생성자에 역할을 위임해서 객체 바인딩이 이루어진다고 하네요.

그런데 getter + AllArgumentConstructor이고 인자가 1개인 생성자일 경우에는 바인딩 되지 않는 예외 케이스가 존재하기 때문에, 
방어코드로 request, response dto 만들 시에는 NoArgumentConstructor 추가하는게 좋을 것 같다는 생각입니다~

2022-11-18 14:39 UTC, Byeongju-Kong requested changes
리뷰를 남기다보니 20개가 되었네요..😅😅😅

전반적인 코드에 대해서 제안 드릴게 몇개 있어서 아래에 남깁니다!
1. 파라미터에 final을 꼭 붙혀야할까요?
final은 참조를 변경할 수 없도록 하는 것이예요. 파라미터는 메서드, 생성자에서 지역변수로 사용되는데 과거에는 메서드가 길었기 때문에, 참조가 어디서 변경되는지 파악하기가 힘들어서 final 키워드가 유용할 수 있었겠지만, 메서드를 가능하면 짧게 가져가야한다는 것은 모두가 동의하는 사실이기 때문에 final 키워드가 없어도 될 것 같다는 생각이 들어요!
물론, 이 부분은 스타일에 따라서 천자만별이라서 고려만해보셔도 좋을 것 같아요. final 키워드를 사용하는 것을 선호하신다면 메서드 내부에서 선언하는 변수들도 같은 지역변수라는 맥락에서 다 final을 붙혀서 사용하는 것이 일관되지 않을까? 라는 생각입니다.
2. Test 코드에서의 when~then~given 
지금 테스트 코드들은 복잡하지 않아서 개인적으로 when~then~given이 불필요하다고 생각합니다. 오히려 코드의 라인만 늘린다고 생각해요. 충분히 개행만으로 when~then~given을 파악할 수 있을 것 같아요.
 테스트코드가 길어지고 when에서도 개행을 해줘야 코드가 잘 읽히는 상황이라면, 그 때는 when~then~given을 통해서 테스트 코드를 파악하도록 하는것이 좋지 않을까? 하는 생각입니다~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/main/java/hamkke/board/service/UserService.java
> +                    log.debug("중복된 아이디 생성 loginId = {}", createUserRequest.getLoginId());
예외 상황에서 logging을 하신 이유가 있나요?

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/main/java/hamkke/board/service/UserService.java
> +        userRepository.findUserByAlias(new Alias(alias))
꼭 Alias 객체를 통해서 조회를 해야할까요? DB에서는 Alias라는 객체를 모를텐데요! Alias에 해당하는 값으로만 조회를 할 수 있는데, 고려해보시면 좋을 것 같아요~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +    private final String password;
DTO에서 `@Notnull` 체크만을 하고 나머지 검증은 값 객체에서 이뤄지네요!
비슷한 맥락에서 사용하는게 `@NotEmpty`도 있고 `@NotBlank`도 있는데요.
DTO에서 어느정도의 검증을 해야하고 값 객체에서 어느 정도의 검증을 해야하는지에 대해서 고민해보시면 좋을 것 같아요!

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +@WebMvcTest(UserController.class)
이건 저도 몰랐네요~ 찾아보겠습니다!

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/bulletin/BulletinTest.java
> +    }
단순한 getter 반환 테스트가 필요할까요? 테스트를 실행하고 유지보수 하는 것도 비용인데요!
테스트라는 것의 목적에 대해서 고려해보셔도 좋을 것 같습니다!

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/bulletin/BulletinTest.java
> +        Bulletin bulletin = new Bulletin("sample title", "sample content", user);
위에 createBulletin 라는 메서드가 존재하는데 직접 생성하신 이유가 있으실까요?
그리고 @DisplayName에 연관 관계 편의 메서드라고만 작성해줘도 될 것 같네요! 
입력 받은 Author 의 게시물과 동일한지 비교한다. 를 봤을 때는, 특정 메서드에 Author가 들어가서 동일한지 비교하는 듯한 느낌이네요!

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/bulletin/vo/ContentTest.java
> +    }
이 테스트의 목적은 무엇인가요? 파라미터로 들어오는 값으로 Content 객체를 잘 생성함을 테스트하기 위함이라면, 예외가 터지지 않음을 검증하는 것이 좋아보이네요! assertThatCode().doesNotThrowAnyException()을 사용하시면 좋을 것 같습니다!

저는 해당 테스트가 eq를 테스트하는 것 같다는 생각이 들어요~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/bulletin/vo/ContentTest.java
> +    @DisplayName("글 내용은 최대 1000 자여야한다.")
```suggestion
    @DisplayName("글 내용은 최소 1자, 최대 1000 자여야한다.")
```

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/bulletin/vo/TitleTest.java
> +        Title title = new Title(testTitle);
위의 Content 테스트에서는 Content에 들어가는 문자열을 따로 변수로 선언하지 않았는데, 여기는 testTitle이라고 따로 선언하셨네요! 이유가 있으신가요?

저는 아래의 경우에 따로 변수로 추출합니다!
1. 할당되는 값이 어떤 값인지를 명시한다.
2. 인라인으로 다 쳐버리기엔, 코드의 한 줄이 너무 길어진다. 

고려해보셔도 좋을 것 같아요~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/user/UserTest.java
> +        // then
여기는 개행이 없네요~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/user/UserTest.java
> +                () -> assertThat(actualAlias).isEqualTo(new Alias("삼다수"))
이건 개인적으로 스타일의 차이라고 생각해서 리뷰 드릴까 고민했는데요. 고민만 해보셔도 좋을 것 같아요!
apple123, apple123!!, 삼다수는 위의 createUser 메서드에서도 사용하고 있어서 하드코딩을 없애고 상수로 추출해도 괜찮을 것 같습니다~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/user/vo/PasswordTest.java
> +    }
```suggestion
        assertThatThrownBy(() -> new Password(inputPassword))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("비밀번호는 영문(대문자,소문자), 특수문자(!,@,#,$,%,^,&,*,_,-), 숫자를 최소 1개 이상 조합한 8자 이상 18자 이하여야합니다.");
    }
```

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +    }
타입을 체크하는 것이 중요할까요? `@DisplayName`에 `회원 가입 성공 시, 회원의 식별 id를 반환한다.`라고 되어있는데요. 
위와 같은 테스트 코드라면 `@DisplayName`이 `회원 가입 성공 시, 반환되는 회원의 식별 id는 Long 타입이다.`라고 되어야 할 것 같아요.
반환을 하는 것을 검증하고 싶으시면 isNotNull()을 사용하는 것도 괜찮은 것 같아요~

2022-11-18 14:39 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/domain/user/vo/PasswordTest.java
> +    }
이건 진짜 개인적인 것도 위와 같이 개행하면 더욱 잘 읽히더라고요~

2022-11-21 09:34 UTC, ch0ijihwan commented on src/test/java/hamkke/board/service/dto/UserResponseTest.java
> +    }
그럼 DTO는 아예 테스트 코드의 필요성이 없다고 생각해도 괜찮을까요?? 
getter를 테스트 하지 않는다면 DTO를 테스트 할 필요성이 없다고 생각합니다.

2022-11-21 09:38 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/UserService.java
> +    }
DB 접근과 관련해서는 고민을 좀 더 해보겠습니다!

일단 예외가 발생 했을 때, 로그를 남겨야 한다고 생각했습니다. 
 debug로 한 이유는 개발 하면서 postman으로 해당 예외처리가 잘 이루어지는지, 단순 개발 레벨에서 예외를 확인해야 한다고 생각해서 debug 레벨 이라고 생각을 했습니다.

2022-11-21 09:47 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +@MockBean(JpaMetamodelMappingContext.class)
이 부분은 잘못 설정한 부분이라, 나중에 변경해두었습니다!

2022-11-21 09:48 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        input.put("alias", "아이폰");
처음에 테스트 코드 공부하면서, 이 방식으로 했었는데, 나중에 변경했습니다!

2022-11-21 09:51 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        actual.andExpect(status().isOk());
`content` 뒤에 `andExpect()` 를 사용하면 `//given, //when, //then` 구조가 안 이루어진다고 생각해서  `actual` 로 변수를 빼서 했었습니다.
이 부분에 대해서 어떻게 생각하시나요??

2022-11-21 09:51 UTC, ch0ijihwan commented on src/main/java/hamkke/board/controller/UserController.java
> +        return ResponseEntity.status(201)
네 변경하도록 하겠습니다!
가독성을 위해서 변경하는게 좋겠네요

2022-11-21 09:59 UTC, ch0ijihwan commented on src/main/java/hamkke/board/domain/base/BaseEntity.java
> +}
이미 설정 해서 쓰고 있습니다!.
이부분은 이전에 리뷰 받은 내용이라서, 인텔리제이 설정 변경 해서 잡아주었습니다

2022-11-21 10:04 UTC, ch0ijihwan commented on src/test/java/hamkke/board/service/UserServiceTest.java
>  @DataJpaTest
- [JpaAuditingConfiguration.class](src/main/java/hamkke/board/config/JpaAuditingConfiguration.java)
를 보시면 `Auditing` 을 위한 설정인 `@EnableJpaAuditing` 이 있습니다.
테스트 코드 실행 시, `@EnableJpaAuditing` 이 있어야만 `BaseEntity`를 사용할 수 있기에 `import(JpaAuditingConfiguration.class)` 를 설정 하였습니다.

2022-11-21 12:37 UTC, seongbeenkim commented on src/test/java/hamkke/board/service/dto/UserResponseTest.java
> +    }
DTO는 아예 테스트 코드 필요성이 없는 것이 아니라, 
DTO에 어떠한 로직도 들어가지 않고 only getter() 만 있다면, 테스트할 필요없다고 생각합니다~
가끔 DTO에 관련 도메인 객체 생성하는 함수 등이 gettet외의 로직이 들어갈 경우에는 테스트해야하고용

2022-11-22 11:01 UTC, seongbeenkim commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        actual.andExpect(status().isOk());
넵 명확히 분리하기 위해서 하셨다면 좋은 것 같아요~

2022-11-22 11:13 UTC, seongbeenkim commented on src/test/java/hamkke/board/service/UserServiceTest.java
>  @DataJpaTest
그렇군요! 그럼 구현하신 테스트 코드 내용으로는 필요없어도 되는 어노테이션인걸로 확인되는데 맞나요?

2022-11-22 13:51 UTC, sdrs6921 requested changes
몇 가지 코멘트 남겼습니다~ 확인 부탁드립니다!

2022-11-22 13:51 UTC, sdrs6921 commented on src/main/java/hamkke/board/service/UserService.java
> +                });
DB에서 발생하는 `동시성` 문제는 고려하신걸까요? user가 회원가입 버튼을 동시에 클릭하거나 분산 환경에서 여러 스레드가 동시에 접근한다면 해당 로직이 의도하신대로 동작할까요?

2022-11-22 13:51 UTC, sdrs6921 commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +    @MockBean
`@MockBean` 애노테이션을 사용하신 이유가 있으신가요?

2022-11-22 13:51 UTC, sdrs6921 commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        given(userService.join(any())).willReturn(1L);
어떤 곳에서는 `BddMockito`를 사용하고 어떤 곳에서는 `Mockito`를 사용하고 계신데, 이 부분을 일관되게 사용하는 것이 좋지 않을까요?

2022-11-22 13:51 UTC, sdrs6921 commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +@DataJpaTest
`Service`에 관한 테스트인데, DB 통합테스트를 진행할 필요가 있을까요?

2022-11-26 08:03 UTC, ch0ijihwan commented
## 변경 사항
- DB 커넥션이 중복되는 부분 변경 하였습니다.
    - 기존에는 1번의 회원 가입 시, 중복 체크로 인해 DB에 3번 접근을 해야했습니다.  
    - 이를 해결하기 위해, DB에 unique 제약조건을 걸어 두었습니다.
    - 하지만 두개의 unique 제약조건에 대한 예외처리를 각각 핸들링을 해주지 못했습니다.
    - 일단 DB 커넥션을 줄이는것을 우선으로해서 변경을 하였습니다.
- 전체적으로 테스트 코드를 변경하였습니다. 
    -  controller service repository 각각 단위테스트를 구현했습니다.
    - 세가지 레이어를 모두 사용하는 통합테스트를 구현했습니다. 

###
질문 사항
DB 접근을 줄이기 위해서 예외처리 핸들링을 세부적으로 못하게 되었는데, 이 부분을 어떻게 처리해야할지 고민입니다. 
결국 
- 1. DB 접근을 자주 하지만, 중복 값 입력시 logId 와 Alias를 각각 예외 핸들링을 하는 방법
- 2. 1번의 DB 접근으로, 중복 값 입력 시 예외 핸들링을 한다.  -> 이 경우 단순하게, loginId 나 alias의 중복 값이 있습니다. 라고 예외가 나감
  이 두가지 방법중 하나를 결정해야하는데, 어떤게 나을까요??


이외로 고민한 다른 방법은
- 1. DB에 unique 제약 조건을 걸고, 일단 insert를 한다.  이때 중복값 예외가 발생하면, 어떤 필드에 대한 예외인지 찾기 위해 DB에 접근한다.
사실 이 방법이 제일 좋은 것 같다고 생각이 되어서 적용해보았습니다. 하지만 두번째 request 접근 시, id 값이 null 처리가 됩니다.. 원인을 찾아보니 한 트랜잭셔널 안에서 여러번 db를 접근하면서 발생하는 문제라는 글을 보았는데, 정확하게는 모르겠습니다..
- 2. 위의 2번째  `1번의 DB 접근으로, 중복 값 입력 시 예외 핸들링을 한다. ` 방법에서 `dataintegrityviolationexception` 예외를 캐치하면 이를 다른 예외로 강제 형변환 시켜서, 어떤 필드에 대한 예외인지 확인하는 방법이 있었습니다. 하지만 이 방법은  `dataintegrityviolationexception` 자체가 스프링이 예외를 한번 감싸준 것인데 이것을 다시 형변환 해서 사용하는 방식이라 지양하는게 좋다고 합니다. 결국 Mysql에 종속적인 로직이 된다고 합니다.

2022-11-27 11:22 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +@DataJpaTest
`@DataJpaTest`에는 `@Transactional` 어노테이션이 붙어있는데요. 그러면 Transaction이 프로덕션 코드에서 열리지 않고, Test 코드에서 열려요. 이런 상황에선 어떤 문제가 있을까요..?

2022-11-27 11:25 UTC, ch0ijihwan commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +@DataJpaTest
test

2022-12-01 10:00 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
> 그런데 getter + AllArgumentConstructor이고 인자가 1개인 생성자일 경우에는 바인딩 되지 않는 예외 케이스가 존재하기 때문에,
방어코드로 request, response dto 만들 시에는 NoArgumentConstructor 추가하는게 좋을 것 같다는 생각입니다~

이부분 관련해서 궁금한 점이 있는데, 현재 코드에서는 필드가 `final` 으로 생성되기 때문에, 위에서 말씀하신 경우가 발생하지 않을거라고 생각되었습니다.

그럼 `final`을 제거하고, `NoArgumentConstructor`를 적용하는게 나을지,아니면 현 상태로 두는게 나을지 궁금합니다!
Dto 에 3개의 필드(logindId, password, alias) 가 null 이 될 상황은 발생하지 않을거라 생각해서 final로 두는게 안전하다고 생각했습니다.

2022-12-01 10:13 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        given(userService.join(any())).willReturn(1L);
변경하였습니다!
`BddMockito` 말고 `Mockito` 를 사용하려고 합니다.

2022-12-01 10:15 UTC, ch0ijihwan commented on src/test/java/hamkke/board/service/UserServiceTest.java
> +@DataJpaTest
이 코드는 원래 제가 UserService 테스트를 단위 테스트로 진행하려고 했었는데, 통합테스트를 하듯이 해버렸습니다..
repository를 mocking 해서 실행되는 Service 단위 테스트로 변경하였습니다.

2022-12-01 10:52 UTC, ch0ijihwan commented on src/test/java/hamkke/board/domain/bulletin/vo/TitleTest.java
> +        Title title = new Title(testTitle);
변수로 한번 빼주는 방식으로 가려고 합니다.
`title` , `content`  테스트 자체가 입력되는 `testTitle`과 `testContent`가 핵심이기에 변수로 빼는게 맞다고 생각했습니다.

2022-12-01 10:53 UTC, ch0ijihwan commented on src/test/java/hamkke/board/domain/user/UserTest.java
> +        // then
변경 해주었습니다

2022-12-01 10:54 UTC, ch0ijihwan commented on src/test/java/hamkke/board/domain/user/UserTest.java
> +                () -> assertThat(actualAlias).isEqualTo(new Alias("삼다수"))
인라인으로 바로 넣어주는게 좀 더  코드를 이해하는데 가독성이 좋다고 생각해서 이렇게 해주었습니다.

2022-12-01 11:17 UTC, ch0ijihwan commented
### 변경사항

- 회원 가입 예외처리 세분화 하도록 변경
- `User entity` 에 `uniqueConstraints` 조건을 명시, `UniqueConstraint name`을 지정함
     - 기존에는 각 vo의 @Column 에  unique = true 설정으로 유니크 제약 조건을 걸어주었던 문제 변경
     - 이로 인해 유니크 제약 조건 위반시, 어떤 컬럼에서 발생했는지 알 수 있도록 함.

---

## 그외

예외처리 부분을 Controller에서 잡는 것으로 해보라고 피드백 주셨는데, id 와 별명의 중복은 서비스 관련 문제라고 생각해서 `serive` 에서 예외를 발생하는게 좋겠다는 생각을 하였습니다. 그래서 `DataIntegrityViolationException` 예외를 `service`에서  세분화된 에러로 발생시키는게 좋다고 생각했습니다.

2022-12-02 02:25 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
아하~ 위에 설명드린 부분은 `final` 키워드 및 `null` 이랑은 상관없는 내용이에요
jackson 맵핑 시 생성자 관련된 내용으로 공유드린 부분이었습니다~

> 현재 코드에서는 필드가 final 으로 생성되기 때문에, 위에서 말씀하신 경우가 발생하지 않을거라고 생각되었습니다.

final로 선언해서 생성되는 것과는 관련이 없어요.

현재 코드에서는 final을 붙여주던 안붙여주던 상관없이 3개의 모든 필드를 가지고 있는 생성자가 있기 때문에 jackson이 객체 매핑을 성공적으로 해줍니다

하지만, final을 붙여주던 안붙여주던 필드 1개이고, 1개의 필드만 있는 생성자를 가질 경우 jackson에서 해당 객체 맵핑 자체가 실패한다는 내용이었어요~
이 부분을 모두가 알 수 있을거라 생각하지 않기 때문에, 일관성있게 dto 객체에는 방어코드처럼 @NoArgumentConstructor 추가해주면 좋지 않을까란 의견을 드린거에용~

> Dto 에 3개의 필드(logindId, password, alias) 가 null 이 될 상황은 발생하지 않을거라 생각해서 final로 두는게 안전하다고 생각했습니다.
일반적인 개념에서 final로 선언해도 null로 초기화가 가능하기 때문에, null이 될 상황은 발생하지 않을 거라 생각해서 final로 두었다는 것은 올바르지 않은 표현인 것 같아요.

final은 최초 초기화 후 값을 변경하지 못하는 의미에서 사용하기 때문에, 해당 값들이 한 번 초기화되고 절대 변경이 일어나지 않는다는 개념으로 붙여주었다고 하시는게 좋은 것 같습니다~

2022-12-02 03:11 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
제가 이해한 바로는 
- 일반적으로 객체 매핑 시, object mapper는 기본 생성자를 통해 객체를 생성하고, 바인딩 시, setter를 통해서 데이터를 주입한다.
- 하지만 스프링 부트를 사용할 경우 jackson-module-parameter-names 를 주입 받기 때문에, 기본 생성자가 없어도 역직렬화를 수행 할 수 있다. 하지만 예외는 존재.
- 그 예외란, 1개의 필드를 가지고 있는 DTO 에서 1개의 필드만을 받는 생성자를 가질 경우 jackson 에서 해당 객체 매핑을 실패 할 수 있다. 
- 따라서 이런 점을 방지하기 위해서, @NoArgumentConstrutor를 선언해, 이런 예외가 존재하지 않도록 방어코드를 명시해두는게 좋다. 
라고 이해하였습니다.

---

>또한 Dto 에 3개의 필드(logindId, password, alias) 가 null 이 될 상황은 발생하지 않을거라 생각해서 final로 두는게 안전하다고 생각했습니다.
이부분은 확실히 제가 말씀을 잘못드렸습니다.  제가 null 이 될 상황은 발생하지 않을 것이라 말씀드린 이유는 프론트에서 공백이거나 empty인 경우는 넘겨주지 않기로 약속을 하였기 때문에 위와 같이 표현하였습니다. 그렇다고 하더라도, final로 선언한 것은  절대 변경이 일어나지 않는 다는 의미인데 null이 안 올 것이라고 잘못 표현했네요..

---

방어코드 관련해서, 추가적으로 final 키워드로 인해서 final로 선언한 필드의 초기화가 꼭 일어나야 하는데, 방어코드로 현재 DTO 에 @NoArgumentConstructor 를 추가하게 된다면, 이런 초기화를 못한다고 생각했습니다. 기본 생성자가 있는 경우 DTO 내부에 3개의 필드를 초기화 할 수 없기 때문입니다.
아래 사진 첨부하겠습니다.

<img width="843" alt="스크린샷 2022-12-02 오후 12 04 43" src="https://user-images.githubusercontent.com/26710955/205205866-8d1d9987-66a5-488f-a83d-974fa14d332f.png">

물른 필드 자체에 직접 초기화를 할 수는 있겠지만, 이렇게 되면 DTO의 기능을 못한다고 생각했습니다. 

따라서 필드가 final인 복수개의 필드를 가진 DTO에 일관적으로  NoArgumentConstructor 를 사용 불가능하다고 생각했습니다.


---

이런 과정으로 final 를 제거하고 NoArgumentConstructor 를 선언하여 방어코드를 적용을 할지, 현 상태로 둘지를 여쭤보았던 것 입니다.

2022-12-02 04:22 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
> object mapper는 기본 생성자를 통해 객체를 생성하고, 바인딩 시, setter를 통해서 데이터를 주입한다.

넵넵 getter / setter!

아하 죄송해요 제가 final 선언 시 noArgument 초기화 하는 부분은 생각하질 못했네요~
현 상태로 두시고, 사실 dto에 1개의 필드만 넣어두는 경우도 거의 없기 때문에 제가 전달드린 내용에 대해서만 알고 있으시면 좋을 것 같습니다!

2022-12-02 04:37 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
네 알겠습니다!

제가 다른 DTO 에서는 1개의 필드만 넣어두는 경우를 만들어두었습니다. 아무래도 final 로 DTO를 불변으로 만들어 두는 것보다, 문제 상황이 발생하지 않는게 더 중요하다고 생각합니다.
따라서 위에서 알려주신대로 문제가 발생할 수 있으니, 이 프로젝트에서는 1개의 필드를 가지는 DTO는 필드의 final 을 제거하고, 기본 생성자를 만들어서 사용하는 방식으로 가겠습니다.

2022-12-02 04:44 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
넵넵, 일관성있게 final로 가져가고 싶으시면 생성자 위에 @JsonCreator 선언해주면 된다고 하니 해당 부분도 알고 있으면 좋을 것 같아요~

2022-12-02 07:09 UTC, sdrs6921 requested changes

2022-12-02 07:09 UTC, sdrs6921 commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +    private final String password;
제약 조건에 관한 내용을 `presentation layer` 한번 더 검증해 줄 수 있으면 좋지 않을까요? 프론트에서만 검증하는 것도 좋지만 서버에서 한 번 더 검증해줄 수 있으면 좋을 것 같아요~

2022-12-02 07:09 UTC, sdrs6921 commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +    @MockBean
그렇다면, `@Mock`으로 해결할 수도 있는데, 그렇게 하지 않으신 이유가 있으신가요?

2022-12-02 07:09 UTC, sdrs6921 commented on src/main/java/hamkke/board/service/UserService.java
> +            }
동일한  예외상황인데, 만약 제약조건이 여러 개인 `entity`면 전부 분기해서 처리하실 예정이신가요?

2022-12-03 14:35 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +    @MockBean
일단 `@Mock` 로 변경하게 되면 `UserService Bean`  을 찾을 수 없다고  에러가 발생합니다.
 현재 코드에서 컨트롤러를 테스트 하기 위해 `@WebMvcTest(UserController.class)`를 사용하였습니다.
 @WebMvcTest  사용 시 사용하는 Bean 의 경우 @MockBean 이나 @Import 로 주입해주어야 한다고 합니다.
그래서 `@MockBean` 을 사용했습니다.

2022-12-03 14:36 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +public class CreateUserRequest {
네 감사합니다!

2022-12-03 15:31 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/UserService.java
> +            }
이 부분 변경중에 있습니다..! 
변경하고 push 올리겠습니다.

2022-12-04 10:14 UTC, Byeongju-Kong commented on src/main/java/hamkke/board/service/UserService.java
> +        userRepository.findUserByAlias(new Alias(alias))
네 맞습니다~!

2022-12-04 12:39 UTC, seonghun127 commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +    @MockBean
해당 테스트 코드는 application context가 형성되는 환경이기 때문에 모킹처리할 객체는 @MockBean 어노테이션이 필요해요~
application context에 모킹된 빈이 등록되어야하기 때문입니다 :)

2022-12-06 06:23 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/dto/CreateUserRequest.java
> +    private final String password;
반영해서 변경하였습니다!

2022-12-06 06:25 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/UserService.java
> +            }
enum으로 관리하는 방향으로 한번 해보려고 합니다.
나중에 문제가 될 경우 수정하도록 하겠습니다.

2022-12-18 08:03 UTC, sdrs6921 approved these changes
몇 가지 코멘트 남겼습니다! 몇 가지 질문 사항이 있어서 질문만 남기고 어프 드렸습니다~! 고생하셨습니다!

2022-12-18 08:03 UTC, sdrs6921 commented on src/main/java/hamkke/board/domain/user/User.java
> +        }
오! `@Table` 애노테이션 내에 선언하셨네요~! 이러한 방식으로 unique 제약 조건을 설정하신 이유가 있으신가요???

2023-01-13 16:23 UTC, merged