Feature/#34/회원 로그인 로직 생성
kodesalon/HamKke pull request #35
Opened 2022-12-07 13:06 UTC by ch0ijihwan

# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #34 
## 변경 사항 
- 회원 로그인 기능을 추가하였습니다.
   
## 그 외
- 세션 및 토근 관련 기능은 다른 이슈에서 적용하는게 나을 것이라 판단해여, login 결과만을 알 수 있도록 하는 로직을 작성하였습니다.

## 질문 사항

- `dto` 를 생성하고, `dto` 내부에 있는 값을 꺼낼 때, `vo`로 사용되는 `passowrd` 나 `alias` 를 계속 `new()` 형태로 생성해주거나, `getAlias().getValue` 등의 로직이 생기게 되는데, 이를 깔끔하게 개선할 수 있는 방법이 있는지 궁금합니다.
   -  아무래도 `User` 엔티티에서 `@Getter`를 사용하였더니, `user.getAlias()` 같은 경우, `Alias` 객체 형태로 반환되기 때문에 별명 값을 알기 위해선 외부에서 `alias.getValue()`형태로 객체 내부의 값을 한번 더 꺼내줘야 하더라고요...
   - 생각한 방법으로는 이전에 다른 미션에서 했던 것 처럼 `Alias` 자체로 `String` 타입을 반환하는 `getAliasValue()` 라는 메서드도 생각해봤는데, 이미 `@Getter` 로 `getter`를 만들어둔 상황에서는 굳이? 라는 생각이 듭니다. 불필요한 getter 만 늘어나는 것 같아요.
   - 다른 방법으로 `dto` 자체에 필드를 `Primitive`타입으로 두지 않고 각각의 `vo` 타입으로 두는 것도 생각을 해보았지만, 이는 비즈니스적인 요소가 DTO 내부에 들어가기 때문에 오로지 데이터의 전달 이라는 특성을 가지는 dto 특징과 맞지 않다고 생각하였습니다.

2022-12-07 17:23 UTC, seongbeenkim requested changes
코틀린 미션하고 잠이 안와 피드백 간단하게 남겼어요~ㅋㅋ

자고 일나서 코드 더 보고 피드백 더 남길만한 것 있으면 남기고 질문에 대한 답변도 남겨놓을게여~

2022-12-07 17:23 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/UserService.java
> +    }
`private void matchPassword(final LoginRequest loginRequest, final User user) `
에서 `loginRequest.getPassword()`만 사용하는데, 이럴 경우 필요한 `password`만 인자로 넘기는 방식으로 구현하면 더 좋을 것 같아요~ 이렇게 객체 통째로 넘겨주게 되면 불필요한 인자에 대한 접근도 가능할 뿐만 아니라, 테스트 코드 짜기도 힘들어집니다~

```suggestion
    private void matchPassword(final String password, final User user) {
        if (user.isInCollectPassword(new Password(password))) {
            throw new IllegalStateException("비밀번호가 일치하지 않습니다.");
        }
    }
```

2022-12-08 07:19 UTC, ch0ijihwan commented on src/main/java/hamkke/board/exception/AllExceptionHandler.java
> +    @ExceptionHandler({IllegalStateException.class, IllegalArgumentException.class, MethodArgumentNotValidException.class,IllegalArgumentException.class})
비즈니스적 예외를 처리해주는 부분과, 바인딩 부분 +  유효성 검사 부분으로 메서드를 나누었습니다.

2022-12-08 07:56 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/UserService.java
> +    }
`user` 에 위임하기보다, `password` 에게 위임하는 것이 더 좋다고 생각하였습니다.
그래서 현재 비밀번호 일치, 불일치 파악 로직을 `password` 에 위임하도록 변경하였습니다.

2022-12-08 08:25 UTC, ch0ijihwan commented on src/test/java/hamkke/board/repository/UserRepositoryTest.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재 하지 않는 ID 입니다."));
> 그리고 .orElseThrow(() -> new IllegalArgumentException("존재 하지 않는 ID 입니다.")); 는 제거해도 좋을 것 같아요~ 
사실 이부분을 조금 고민했었는데, 옵셔널 인자로 값이 반환되기 때문에 `User` 에 접근할려면 `.orElseThrow` 예외처리를 사용해서 꺼내 주는게 맞다고 생각했습니다.

`.get()` 으로 `User` 인자를 꺼내도 괜찮을까요? 아니라면 ` .orElse()` 를 사용해야하는데 이는 더 아닌거 같아서 고민입니다.

2022-12-08 08:25 UTC, seongbeenkim commented on src/main/java/hamkke/board/controller/UserController.java
> +        log.info("login 요청 loginId = {}, password = {}", loginRequest.getLoginId(), loginRequest.getPassword());
추후 다른 개발 다 하고 개인정보 암호화 적용해봐도 좋을 것 같네요!

2022-12-08 08:33 UTC, ch0ijihwan commented
# 변경 사항

 -  UserService 에서 비밀 번호 매칭하는 부분을 Password 로 위임 하였습니다.
 - 테스트 코드 mocking 순서를 변경하였습니다.
 - 예외 핸들러 부분을 세부적으로 나누는게 좋다고 생각해서, validation 역할 처리 메서드와 비즈니스 관련 예외 처리로 메서드로 나누었습니다.

---

## 질문 사항

변경하면서 비밀번호 불일치에 해당하는 예외를 어디에서 터트려야할지 고민이 있었습니다.
처음엔 Password 에서 예외를 생성을 하였으나, 이렇게 될 경우 UserService에서 `비밀번호 불일치` 예외를 파악하기 어렵다 생각했습니다. 하지만 비밀번호 관련 예외이기 때문에 Password 가 역할을 갖는게 맞다는 생각도 들었습니다. 

하지만 Login 관점에서 `비밀번호의 불일치` 를 명시 해야하는게  더 중요하지 않나? 라는 생각도 했습니다. password 에서는 단순히 비밀번호가 매칭되는지, 아닌지만 확인하는 matchPassword 메서드를 만들었고, UserService 에서 예외를 반환하도록 변경하였습니다.

보통 어떻게 이런 문제를 처리하지는지 궁금합니다.

2022-12-09 06:40 UTC, ch0ijihwan commented on src/test/java/hamkke/board/repository/UserRepositoryTest.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재 하지 않는 ID 입니다."));
조언해주신 부분 반영해서 변경하였습니다!

2022-12-13 05:39 UTC, ch0ijihwan commented
# 변경 사항

 - 비밀번호 매칭 시, 일치 하지 않는 예외를 password에서 생성하도록 변경하였습니다.
     - 이전에 boolean값을 반환하던 로직을 void 로 변경하였습니다.
     - 위의 변경 사항에 따라 테스트 코드도 변경하였습니다.
 - 예외처리를 명확하게 나눌 수 있도록 해보았습니다. 
     -  IllegalArgumentException 같은 경우, 값을 입력받았을 때 발생하는 로직(전달 받은 비밀번호 매칭, 전달 받은 값에 대한 유효성 검사) 등에서 사용하였고
     - IllegalStateException 같은 경우, 중복성 검사에서 사용하도록 변경하였습니다.

## 질문 사항

이번에 Password 매칭 로직을 void 로 처리하도록 변경하면서 테스트 코드의 변경이 일어났습니다.
테스트 코드 작성 중, 예외처리가 발생하는 부분을 mocking 하려 했으나, 기존에 when(메서드).thenThrow(발생할 예외) 처럼 하니 mocking이 안되었습니다.
찾아보니 리턴타입이 void 인 메서드를 모킹 할때는, 방식이 조금 다른 것을 알게되었습니다. 그래서 하단과 같이 변경하였습니다.
해당 테스트 코드 변경이 적절한지 궁금합니다.

![스크린샷 2022-12-13 오후 2 33 19](https://user-images.githubusercontent.com/26710955/207234862-7b65968b-c70c-4826-9ef6-6c8686a2f79f.png)

2022-12-17 01:56 UTC, seongbeenkim approved these changes
넵넵 테스트 코드 변경 void일 경우 doThrow() 좋은 것 같아요~

2022-12-17 01:56 UTC, seongbeenkim commented on src/main/java/hamkke/board/exception/AllExceptionHandler.java
>      }
`handleBusinessException` 은 잘못된 요청이 아니라 500 내부 서버에러로 처리하면 좋을 것 같아요

2022-12-17 01:56 UTC, seongbeenkim commented on src/main/java/hamkke/board/exception/AllExceptionHandler.java
`handleBusinessException` 는 500 internal error로 보내는게 좋을 것 같아영

2022-12-18 08:12 UTC, sdrs6921 approved these changes
질문하신 내용에 대한 답변과 한 가지 질문 사항이 있어서 코멘트 남겼습니다~! 특별히 문제가 되는 부분은 없어서 어프 드리겠습니다! 고생하셨습니다~!

2022-12-18 08:12 UTC, sdrs6921 commented on src/main/java/hamkke/board/repository/UserRepository.java
> +    Optional<User> findByLoginId(final LoginId loginId);
질문 하신 내용 중에, String 값으로 사용하시고 있으신 것 같아서 코멘트 남깁니다. 사용할 수 있는 방법이 있고, 메서드명에 필드 명을 추가로 더 붙이면 String으로 조회가 가능합니다~!

2022-12-18 08:12 UTC, sdrs6921 commented on src/test/java/hamkke/board/repository/UserRepositoryTest.java
> +        softly.assertThat(findUser).isNotEmpty();
음... 사실 이 부분은 취향차이이지만,  `isNotEmpty()`만 테스트해줘도 괜찮지 않을까요? 이미 아래 테스트는 다른 곳에서 수행하지 않나요??? 여기에 있는 테스트를 통해 어떤 부분을 검증하고 싶으신 건가요?

2022-12-22 06:15 UTC, ch0ijihwan commented on src/main/java/hamkke/board/exception/AllExceptionHandler.java
>      }
반영하였습니다.

2022-12-22 07:43 UTC, ch0ijihwan commented on src/main/java/hamkke/board/repository/UserRepository.java
> +    Optional<User> findByLoginId(final LoginId loginId);
`findByLoginId_Value(String loginId)` 로 변경하여 , String 값으로 바로 조회할 수 있도록 변경 하였습니다.

2022-12-22 07:46 UTC, ch0ijihwan commented on src/test/java/hamkke/board/repository/UserRepositoryTest.java
> +        softly.assertThat(findUser).isNotEmpty();
다른 곳에서 수행하는 테스트라는 것이   

> softly.assertThat(findUser.get().getLoginId()).isEqualTo(new LoginId("apple123"));
        softly.assertThat(findUser.get().getAlias()).isEqualTo(new Alias("삼다수"));

이 부분이 User 엔티티에 대한 테스트라고 생각하셔서 말씀해주신 것인가요??

제가 이 테스트로 확인하려고 했던 것은 입력한 loginId 를 통해, 해당 loginId를 가진 User 객체가 잘 반환되는지 확인하려고 했습니다.

2022-12-29 10:23 UTC, sdrs6921 approved these changes
질문을 통해 의도하신 내용을 파악하였습니다! 한 가지 코멘트 남겼는데, 사소한 부분이라서 어프 눌렀습니다!

2022-12-29 10:23 UTC, sdrs6921 commented on src/main/java/hamkke/board/repository/UserRepository.java
> +    Optional<User> findByLoginId_Value(String loginId);
Wrapping된 객체 말고 직접 파라메터로 받는 방법을 사용하셨네요 👍🏻 
그런데 `_`가 필요한가요?

2022-12-29 10:23 UTC, sdrs6921 commented on src/test/java/hamkke/board/repository/UserRepositoryTest.java
> +        softly.assertThat(findUser).isNotEmpty();
말씀하신 부분을 테스트하시는 의도라면 아래 값을 검증하는 것도 좋은 방식이네요~! 👍🏻

2022-12-30 06:42 UTC, ch0ijihwan commented on src/main/java/hamkke/board/repository/UserRepository.java
> +    Optional<User> findByLoginId_Value(String loginId);
자동완성 기능으로 확인했을 때, 최상단에 `_` 가 있어서 해당 메서드로 만들어두었습니다.

`_` 를 제거해도 의도한 로직이 실행되는 메서드가 생성되니 변경해주었습니다.

2023-01-13 15:46 UTC, seonghun127 commented
approve가 2개이니 merge 가시죠! :)

2023-01-13 16:19 UTC, merged