Feature/유저 및 게시판 엔티티 구현
kodesalon/HamKke pull request #4
Opened 2022-10-16 07:31 UTC by ch0ijihwan

유저 및 게시판 엔티티 구현했습니다.

변경 사항 
- 기존에 만들어 두었던, 회원가입 조건에 따른 객체들과, 게시글 조건에 따른 객체들을 엔티티의 값 객체로 쓰기 위해 변경
- 엔티티 Bulletin, User 생성
- 기존에 UserId 였던 값 객체가 User 엔티티의 id와 충돌하는 문제가 생겨, UserId-> UserLoginId 로 이름 변경

그 외
- 값 객체 예외처리 메시지 문구 변경

---
질문 사항
지금과 같이 엔티티를 구현하기 위해서 
이전에 다른 feature 브랜치에서 구현 해둔 password, userId, Alias 등 객체를 pull merge 해와서 변경을 하는 방식이 맞는 방식인건가요?

이미 Pr날린 회원가입 조건 ( password, userId, Alias ) 등에 대한 수정은 새롭게 만든 엔티티 구현 브랜치에서 하는것이 맞는지 궁금합니다.

2022-10-16 12:10 UTC, seongbeenkim commented on board/src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +    }
author를 변경하는 것이기 때문에 메소드 이름이 changeAuthor로 변경하는 것이 좋아보이고,

user.getBulletins().add(this); 역할도 user 객체에 위임하는것도 좋아보입니다~

2022-10-16 12:11 UTC, seongbeenkim commented on board/src/main/java/hamkke/board/model/user/User.java
> +    private final List<Bulletin> bulletins = new ArrayList<>();
User가 회원탈퇴 시, 관련된 게시물도 모두 삭제할 것인지에 대한 규약도 모두 정하고 해당 코드 작성해주신걸까요?

2022-10-16 12:13 UTC, seongbeenkim commented on board/src/main/java/hamkke/board/model/user/vo/UserLoginId.java
> +public class UserLoginId {
User Entity안에 속한 값으로 사용되기 때문에 User prefix는 제거해줘도 좋을 것 같다고 생각이 듭니다~

2022-10-16 12:14 UTC, seongbeenkim commented on board/src/main/java/hamkke/board/model/user/vo/UserLoginId.java
> +    @Column(name = "userLoginId")
위 코멘트와 동일~

2022-10-16 12:15 UTC, seongbeenkim commented on board/src/main/java/hamkke/board/model/user/vo/UserLoginId.java
> +    }
위에서는 userLoginId고 파라미터는 userId로 받고 있는데, 일관성있는 이름으로 가져가면 좋을 것 같습니다.

2022-10-16 12:15 UTC, seongbeenkim commented on board/src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +    private final LocalDateTime createdDateTime = LocalDateTime.now();
변수로 빼신 이유가 있으실까요?

2022-10-16 12:16 UTC, seongbeenkim commented on board/src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +}
TDD 개발하신다고 알고있는데,
Bulletin.changeUser() 메서드는 존재하지만, 테스트 코드는 없네요~

2022-10-16 12:17 UTC, seongbeenkim commented on board/src/test/java/hamkke/board/model/user/UserTest.java
> +    LocalDateTime createdDateTime = LocalDateTime.now();
이것도 변수로 빼신 이유가 있을까요?
그리고 여기는 왜 private final을 선언해주지 않으신걸까요?

2022-10-16 12:21 UTC, seongbeenkim requested changes
JPA 관련된 내용은 크게 리뷰할 게 없어 보이네요~
궁금한 점, 수정하면 좋은 점 코멘트 남겨드렸습니다~

2022-10-29 14:56 UTC, ch0ijihwan commented
Can one of the admins verify this patch?

2022-11-05 12:13 UTC, ch0ijihwan commented on board/src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +    private final LocalDateTime createdDateTime = LocalDateTime.now();
테스트 코드가 더 추가 됨에 따라서 똑같은 title, content, author, createdDateTime이 사용될 것이라 생각해, 상단에 빼두었습니다.

현재 상태로는 테스트 코드가 하나만 있기에 불필요한 것 같습니다..

2022-11-05 12:17 UTC, ch0ijihwan commented on board/src/test/java/hamkke/board/model/user/UserTest.java
> +    LocalDateTime createdDateTime = LocalDateTime.now();
추가적으로 테스트 코드가 더 작성될 것 이라 생각해서 여러번 사용 될 것이라 생각해 상단에 뺴두었습니다. 
변경하도록 하겠습니다.. 
private final 도 변경 하겠습니다

2022-11-05 12:48 UTC, ch0ijihwan commented on board/src/main/java/hamkke/board/model/user/User.java
> +    private final List<Bulletin> bulletins = new ArrayList<>();
네 회원 탈퇴 시, 그 해당 회원의 게시물도 같이 삭제하기로 정했습니다. 
따로 게시물을 복구하는 기능은 염두해두지 않고 있었습니다.

2022-11-05 16:07 UTC, ch0ijihwan commented
## 변경 요약

이전 리뷰 사항 수정하였습니다.
또한 그동안 다른 브랜치에서 변경된 사항들이 몇 가지 있어서 merge 후 작업 했습니다. 
- pr #14 
- pr #2  -> 충돌 문제가 일어나서, 머지 및 [수정](https://github.com/kodesalon/HamKke/pull/4/commits/0f6d137b92158885cd65b4a5c58aff5466a85424) 을 하였습니다. -> 해결과정에서 조금 의아한 일이 있었는데, 이 부분은 일요일날 공유해드리겠습니다.

그리고 테스트 코드를 몇번 수정 했습니다.
- 테스트용 객체 안에 들어가는 값 객체들을 미리 생성할지, 각 테스트에서 생성할지 고민하면서 변경 사항이 있었습니다.
- 엔티티 생성시 생성자 파라미터로 String value를 받아 생성자 안에서 값 객체를 생성 하도록 수정하였습니다.

## 질문사항
제가 `bulletin` 과 `User` 사이의 연관관계 편의 메서드를 따로 만들지 않고, `Bulletin` 생성자 내부에서 바로 연관관계를 이어줄 수 있도록 하였습니다. 이런 방식으로 해도 될까요? 

이전에 영한님 강의에서는 `changeAdd()` 라는 연관관계 편의 메서드를 만드는 방식을 배웠고 이럴 형태를 많이 쓴다고 들었습니다. 생성자에서 d이런 연관관계를 잇는 행위를 하지는 않았어요..

그런데 구현하다보니까 이렇게 할필요가 없다고 생각했습니다. 그 이유로는 `Bulletin` 에는 `User` 가 생성자 주입 방식으로만 주입되기 때문에 생성자에서 바로 연관관계를 잇는게 나을 것 같다고 생각했습니다. 그리고 앞으로 `Bulletin` 내에서 `User` 가 변경할 일도 없기 때문에 굳이 메서드를 하나 더 만들어서 할 필요가 없다고 생각했습니다.

2022-11-06 00:50 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +    private LocalDateTime lastModifiedDateTime;
`생성 시간`, `수정 시간`을 지환님께서 직접 업데이트 할 경우를 어떤 이점과 단점이 있는 지 생각해보면 좋을 것 같아요~

`생성 시간, 수정 시간 직접 주입`
- 장점
실제 생성 / 수정 요청 시간을 Controller에서 받아와서 넣어줄 경우, 실제 요청 시간을 저장할 수 있으니 정확한 정보를 가질 수 있다.

- 단점
생성 / 수정 요청 시를 위한 직접 업데이트 하는 함수를 추가 및 매번 호출해야한다.
`Bulletin`, `User` 등 여러 도메인에 같은 역할을 가진 `createdDateTime`과 같은 동일한 컬럼 및 함수가 여러 곳에 중복으로 존재하게 된다.

`생성 시간, 수정 시간 자동 주입` 할 경우의 장/단점을 생각해보고 방법도 찾아보시고, 
프로젝트 정책 방향을 기준으로 어떤 방식으로 가져갈 지 생각해보면 좋을 것 같아요~

2022-11-06 00:55 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/vo/Content.java
> +public class Content {
`Content`는 도메인 내부 값 객체로 사용되는 객체이기 때문에 `AccessLevel.PROTECTED` 가 아니여도 될 것 같아요.
이 부분은 Entity에서 `AccessLevel.PROTECTED` 를 선언해준 이유를 찾아보시면 될 것 같습니다~

2022-11-06 01:27 UTC, seongbeenkim requested changes
질문에 대한 답변 및 코멘트 추가로 남겼어용~

2022-11-06 01:27 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +    }
> 제가 bulletin 과 User 사이의 연관관계 편의 메서드를 따로 만들지 않고, Bulletin 생성자 내부에서 바로 연관관계를 이어줄 수 있도록 하였습니다. 이런 방식으로 해도 될까요?

직접 연관설정할 경우 연관 설정 코드 빼먹을수도 있기 때문에 
생성자에서 연관관계를 이어주는 행위 좋다고 생각해요~

2022-11-06 01:27 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +    private LocalDateTime lastModifiedDateTime;
`생성 시간`, `수정 시간`을 지환님께서 직접 업데이트 할 경우를 어떤 이점과 단점이 있는 지 생각해보면 좋을 것 같아요~

`생성 시간, 수정 시간 직접 주입`
- 장점
실제 생성 / 수정 요청 시간을 Controller에서 받아와서 넣어줄 경우, 실제 요청 시간을 저장할 수 있으니 정확한 정보를 가질 수 있다.

- 단점
생성 / 수정 요청 시를 위한 직접 업데이트 하는 함수를 추가 및 매번 호출해야한다.
`Bulletin`, `User` 등 여러 도메인에 같은 역할을 가진 `createdDateTime`과 같은 동일한 컬럼 및 함수가 여러 곳에 중복으로 존재하게 된다.

`생성 시간, 수정 시간 자동 주입` 할 경우의 장/단점을 생각해보고 방법도 찾아보시고, 
프로젝트 정책 방향을 기준으로 어떤 방식으로 가져갈 지 생각해보면 좋을 것 같아요~

2022-11-06 01:27 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/vo/Content.java
> +public class Content {
Entity에서 `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 를 선언해준 이유는 지연 로딩 시 도메인 객체를 상속받아 Proxy 객체 생성을 해줘야하기 때문인데,

`Content`는 도메인 내부 값 객체로 사용되는 객체이기 때문에 `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 선언 안해줘도 될 것 같아요~

2022-11-06 01:27 UTC, seongbeenkim commented on src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +    }
테스트 코드 관련 남겨주신 질문에 대한 답변드리자면

저는 개인적으로 하나의 테스트 코드 안에 given, when, then이 모두 들어가는 것을 선호합니다. 
즉, 각 테스트에서 객체 생성을 가져간다~

다른 사람들이 각 테스트 코드 영역만 보고 테스트에 대한 전체 맥락을 한번에 파악할 수 있기 때문입니다~

그런데 각 테스트 코드에서 중복되는 객체 생성 코드 등이 나온다면?
객체 생성 함수를 내부 메소드로 빼거나 하는 등의 방식으로 가져갑니다~

2022-11-12 10:49 UTC, ch0ijihwan commented
## Auditing 적용

`Base Entity`  를 생성해 `엔티티의 생성 시점`, `수정 시점`을 기록할 수 있도록 하였습니다.

###수정 이유 
- Bulletin 과 User 엔티티의 코드 중복을 제거

---

### 그 외 사항
- [이전 리뷰 내용](https://github.com/kodesalon/HamKke/pull/4#discussion_r1014754251)

처음에는 단순히 중복을 제거하고자 `Auditing`을 적용하기로 하였고, 그래서 우선 코드의 변경이 많이 가지 않는 선에서 중복을 제거와 엔티티의 생성과 변경에 대한 정확한 시간(실제 요청 시간)을 기록하는게 중요하도 생각했습니다. 따라서 실제 요청 시간을 생성자로 받아서 업데이트를 해주는 방식으로 `Base entity`를 적용하였습니다.

하지만 생각해보니까, 꼭 이걸 유지할 필요는 없다고 생각했습니다.
`controller`에서의 실제 요청 시간과 엔티티 생성시간에 자동으로 생성되는 시간과 크게 차이가 없다고 생각했습니다.

2022-11-12 15:55 UTC, seongbeenkim requested changes
Base Entity 적용해주신 이유 및 반영 내용 확인했습니다~
앞으로 다른 프로젝트 개발하실때도 생성 / 수정 시간을 정확하게 가져가야하는 서비스라면 외부에서 요청, 수정 시의 시간을 받아와서 반드시 직접 업데이트 해줘야한다.
시간의 정확성이 중요하지 않다면, 직접 업데이트 할 필요는 없다 이런 기준을 두고 개발하시면 좋을 것 같아요

Bulletin Cascade 설정해주신 부분 때문에 request change 요청 드립니다~

2022-11-12 15:55 UTC, seongbeenkim commented on src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +                () -> assertThat(author).isEqualTo(user)
assertAll 사용하는것도 잘하셨는데, Soft Assertions 라는 것도 한번 찾아보세용~

2022-11-12 15:55 UTC, seongbeenkim commented on src/test/java/hamkke/board/model/bulletin/BulletinTest.java
> +        assertThat(bulletin.getAuthor().getBulletins()).contains(bulletin);
author가 본인이 작성한 게시물인지를 확인하는 역할을 가져가게 하는 메소드 있으면 더 좋을 것 같네요~

2022-11-12 15:55 UTC, seongbeenkim commented on src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
어떤 이유에서 `cascade = CascadeType.ALL` 을 Bulletin에서 해주셨을까요??

2022-11-13 04:52 UTC, ch0ijihwan commented
## 변경 사항
- `author` 가 작성한 게시물인지 판단하는 메서드 추가
- 테스트 코드 변경 
   - `assertAll` 사용 방식을  `Soft Assertions`  방식으로 변경
   - `cascade` 설정 제거

2022-11-22 13:31 UTC, sdrs6921 requested changes
몇 가지 코멘트 남겼습니다~
확인 부탁드릴게요!

2022-11-22 13:31 UTC, sdrs6921 commented on src/main/java/hamkke/board/model/user/User.java
> +public class User extends BaseEntity {
`User` 엔티티의 동등성은 어떻게 비교할 수 있을 지 고민해보면 좋을 것 같습니다~

2022-11-22 13:31 UTC, sdrs6921 commented on src/test/java/hamkke/board/model/bulletin/vo/TitleTest.java
> +    @DisplayName("글 제목은 1글자 이상 25자 이하여야합니다.")
이전에 남긴 [리뷰](https://github.com/kodesalon/HamKke/pull/2#discussion_r1029296592)와 동일합니다~

2022-11-22 13:31 UTC, sdrs6921 commented on src/main/java/hamkke/board/model/bulletin/Bulletin.java
> +                .equals(author.getId());
`Author` 엔티티의 동등성을 비교할 수 있다면 getId를 각각 꺼내서 비교하는 로직이 필요없지 않을까요~?? 추가적으로 파라메터로 `Author`를 받아서 예외 처리와 같은 비즈니스 로직을 도메인에서 처리하는 방법은 어떨까요? 지환님이 고민하시고 더 좋은 방법이라고 생각하는 방식으로 구현하시면 좋을 것 같습니다~

2022-11-22 13:31 UTC, sdrs6921 commented on src/test/java/hamkke/board/model/user/UserTest.java
> +        SoftAssertions softly = new SoftAssertions();
`SoftAssertions`를 사용하신 의도가 무엇인가요?

2022-12-02 06:57 UTC, sdrs6921 reviewed
궁금한 점이 있어서 질문 드렸습니다! 확인 부탁드려요~

2022-12-02 06:57 UTC, sdrs6921 commented on src/test/java/hamkke/board/model/user/UserTest.java
> +        SoftAssertions softly = new SoftAssertions();
어떤 부분은 `assertAll()` 메서드를 사용하셨는데, 두 가지가 어떤 차이점이 있나요? 그리고 두 가지중 하나로 통일해야 일관성이 유지되지 않을까요?

2022-12-18 07:54 UTC, sdrs6921 approved these changes
몇 가지 코멘트만 확인해주신다면 어프받을 코드라고 생각하여, 어프 드립니다~! 코멘트만 확인해주세요! 고생하셨습니다~!

2022-12-18 07:54 UTC, sdrs6921 commented on src/test/java/hamkke/board/model/user/UserTest.java
> +        SoftAssertions softly = new SoftAssertions();
아 다른 PR에서 확인했을 때, `assertAll()` 메서드를 사용하신 것으로 보여서, 두 가지의 차이점을 인지하고 있으신지와 일관성있게 사용하고 계신지 궁금해서 드린 질문이었습니다~!

2022-12-18 07:54 UTC, sdrs6921 commented on src/main/java/hamkke/board/model/user/User.java
> +public class User extends BaseEntity {
답변 주신 내용으로는 id 값으로 equalsAndHashCode를 생성한다고 하셨는데, 적용하신걸까요?

2023-01-13 15:38 UTC, seonghun127 commented
PR이 너무 오래 묵혀있으면 작업했던 내용들, 리뷰들, 이를 반영했는지 여부 등을 기억하기 힘들어져요.
위 점이 우려되어 리뷰반영이 끝났다면 다시 확인요청을 드리거나, 아직 리뷰 반영이 안됐다면 리뷰반영부터 하는걸 추천드려요~

노파심에 이야기드린거긴하나 지환님이 계획하신 일정대로 작업해주시고, PR 정리도 일정에 포함시켜서 진행해주세요! :)

화이팅입니다.

2023-01-13 16:31 UTC, ch0ijihwan commented on src/test/java/hamkke/board/model/user/UserTest.java
> +        SoftAssertions softly = new SoftAssertions();
assertAll()과 assertSoftly 의 가장큰 차이점은 
assertSoftly 같은 경우 테스트를 실패한 테스트 코드의 라인 위치를 알려주기 때문에, 테스트 확인 시 더 간편한점이 있다고 알고있습니다!

2023-01-17 06:46 UTC, seongbeenkim approved these changes

2023-01-17 06:46 UTC, seongbeenkim commented on src/main/java/hamkke/board/domain/user/User.java
> +    }
User의 `id` 컬럼 기준으로 equals() hashCode() 재정의하신 이유가 궁금해요~

2023-01-17 12:45 UTC, ch0ijihwan commented on src/main/java/hamkke/board/domain/user/User.java
> +    }
비슷한 질문을 희상이형 께서 주셔서 링크 달아두겠습니다!

 https://github.com/kodesalon/HamKke/pull/4#discussion_r1030097894

2023-01-17 12:46 UTC, ch0ijihwan commented on src/main/java/hamkke/board/domain/user/User.java
> +    }
이 당시에는 위의 공유드린 내용으로 생각을 해서, `id` 컬럼을 기준으로 `equals()`, `hashCode()` 를 적용하였습니다.

그런데 지금 생각해보면 비즈니스 키 값의 역할을 `LoginId`가 수행할 수 있다고 생각됩니다.

2023-01-19 11:56 UTC, seongbeenkim commented on src/main/java/hamkke/board/domain/user/User.java
> +    }
넵넵 이해했습니다~ 잘하셨어요~

2023-01-19 12:06 UTC, merged