Feature/#38/jwt 적용
kodesalon/HamKke pull request #40
Opened 2022-12-14 15:08 UTC by ch0ijihwan

# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- jwt 적용을 위한 jwt 의존성 주입
- jwt 생성, 유효검사, 토큰 값 확인 메서드 구현
   
## 그 외
- 우선 jwt 생성, 유효검사, 토큰 값 확인 기능을 책임지는 클래스를 만들었습니다. 공부하면서 하다보니 전체적인 jwt 적용을 하는데는 시간이 조금 걸릴거 같아 끊어서 push 올렸습니다.

## 질문 사항
- 없음

2022-12-15 12:42 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- 토큰 생성에 따른 controller, service 레이어에 대한 변경
- LoginUserArgumentResolver 생성 및 적용
   
## 그 외
- 토큰을 처리하는 argumentResolver를 생성했는데, 리서치하면서 제 나름대로 적용해보았습니다. 이 부분을 중점으로 리뷰를 받고 싶습니다..!

## 질문 사항
- 없음

2022-12-17 02:08 UTC, seongbeenkim commented on src/main/java/hamkke/board/controller/UserController.java
> +                .body(new LoginResponse(loginServiceResponseDto.getUserId(), loginServiceResponseDto.getAlias()));
`@jsonIgnore` 로 token은 직렬화 안되게 막을 수 있을 것 같은데
`LoginResponse` `LoginServiceResponseDto` 두 개 다 가져가시는 이유가 무엇인지 궁금합니다

2022-12-17 02:13 UTC, seongbeenkim commented on src/main/java/hamkke/board/web/argumentresolver/LoginUserArgumentResolver.java
> +}
`TokenResolver` 로그인 요청마다 생성되게 하는 것은 불필요할 것 같아요

그리고 해당 메소드에서는 argument(userId)를 꺼내오는 역할만 가져가고 
토큰 유효성 검증은 앞단 interceptor에서 가져가는 것이 더 좋지 않나라고 생각이드네요!

2022-12-17 03:24 UTC, seongbeenkim requested changes
ArgumentResolver 구현 잘해주셨네요~

토큰 관련한 내용은 다른 부분들 리뷰 반영 후 이야기하면 좋을 것 같아서 코멘트 안남겼습니다~

2022-12-17 03:24 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
어떤 의도로 하신건지는 알겠는데,

`tokenResolver.createToken()`은 사실상 예외 발생 로직이 존재하지 않죠?
그리고 해당 테스트 코드를 보면 token이 어떤 타입으로 나오는지를 알 수가 없는 것 같아서, 어떤 토큰을 반환하는지도 이해하기 힘들 것 같아요.
반환되는 token이 Long, String, custom 객체인지 이런걸 모르기 때문에 명확히 반환해서 그 값에 대한 empty나 null이 아닌 것을 증명하는 게 더 좋지 않나라고 생각합니다.

assertThatCode()는
`assertThatCode(() -> new User("name", 1L)).doesNotThrowAnyException();`
`assertThatCode(() -> password.checkPassword("password")).doesNotThrowAnyException();`
이런식으로 명확히 error가 발생할 수 있는 상황에 관련하여 사용할 때가 더 적합하지 않나라고 생각해요~

2022-12-17 03:24 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +        Key invalidKey = new SecretKeySpec(invalidSecretKeyBytes, SignatureAlgorithm.HS256.getJcaName());
`new SecretKeySpec()` 생성 로직이 `tokenResolver.createToken()`에는 안들어간 것으로 확인되는데
해당 메서드에는 안 넣어주시고 테스트 코드에는 넣어주신 이유가 있나요?

2022-12-18 04:34 UTC, ch0ijihwan commented on src/main/java/hamkke/board/controller/UserController.java
> +                .body(new LoginResponse(loginServiceResponseDto.getUserId(), loginServiceResponseDto.getAlias()));
이 부분, 해결 할 수 있지 않을까 고민하다가,, 결국 DTO를 따로 만들어서 적용했습니다.
`@jsonIgnore` 생각 못했었는데... 반영하겠습니다!!

2022-12-18 05:19 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/argumentresolver/LoginUserArgumentResolver.java
> +}
제가 @Component 를 사용하지 않고, tokenReslolver를 직접 생성한 이유는 Interceptor 에서 autoWired 가 되지 않아, 수동으로 빈을 등록하였고 @Component를 제거 해주었습니다. 


이 부분에 대한 해결책을 찾아서, 현재 반영중에 있습니다. 따라서 TokenResovler 를 @Compoent를 통해서 빈으로 등록하겠습니다.

이에 따라서 TokenResolver 를 사용하는 다른 곳에서도 스프링 빈을 자동주입 받아서 사용할 수 있도록 변경하겠습니다.

2022-12-18 05:19 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
테스트 코드에서는 각각의 테스트 코드가 독립적으로 테스트 되는게 좋다고 생각해서, 각 테스트 마다 객체 생성을 하는게 좋다고 생각했습니다.

2022-12-18 06:49 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
TokenResolver 클래스 자체가 유틸성 클래스처럼 사용되기 때문에 
독립적으로 테스트되는 것과 상관이 없어보이는데, 어떤 점에서 독립적으로 테스트된다고 생각하셨는지 말씀해주실 수 있으실까요??

2022-12-18 07:41 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
단순하게 각 테스트 마다 테스트에서 중요하게 사용되는 `TokenReslover` 객체를 다시 생성해 주는게 좋다고 생각했습니다.
제가 UserTest 에서 각 테스트에서 사용되는 User를 생성하는 메서드를 뽑은 것 처럼

`class UserTest {

    private User createUser() {
        final String loginId = "apple123";
        final String password = "apple123!!";
        final String alias = "삼다수";
        return new User(loginId, password, alias);
    }
`
테스트 때 사용되는 TokenResolver를 사용 할 때마다 생성해주는게 좋다고 생각했습니다.

2022-12-18 07:57 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
근데 생각해보니까..
위의 `User` 예시는 모든 테스트 상황에서 `createUser()`를 쓰지 않는 점과, 중복 코드를 제거해주기 위해 적용했는데
현 TokenResolver에서 매번 생성을 해주는 것에 대한 예시가 되는거 같지가 않네요.

TokenResolver를 상단에 생성해두고, 사용하는 것이 더 나은 코드라고 생각합니다.
더군다나,같은 객체를 매번 생성해주는게 테스트 성능 관점에서 좋지가 않아서, 매번 재생성 해주는게 좋지 않다고 생각합니다..
변경하겠습니다.

2022-12-18 08:02 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
JwtToken 을 생성하는 코드가 중복되어 사용될 것이라고 예상해서, 메서드로 따로 분리를 해두었습니다.

현시점에서는 한번 밖에 사용하지 않기 때문에, 굳이 필요한 코드가 아니네요..  변경하겠습니다.

2022-12-18 11:54 UTC, Byeongju-Kong commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        when(userService.login(any(LoginRequest.class))).thenReturn(loginServiceResponseDto);
when라인이랑 thenReturn라인은 개행 처리해주는게 가독성 측면에서 좋을 것 같은데 어떻게 생각하시나요~?

2022-12-20 01:41 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
제가 말씀드리고 싶었던 부분은 테스트 코드에서 성능, 중복 코드 제거 등 이런 이점을 가져가기 위함이 아니에요.

TDD로 개발하신다고 하셨는데, 테스트 코드 작성 전 구현하려는 클래스가 어떤 역할을 가지는 지 명확히 정의가 되었다면 
TokenResolver는 매번 생성되는 객체가 아닌, spring bean으로 관리되거나 util성으로 싱클톤 클래스로 정의가 되었을 것이고 new로 객체 생성하는 코드 자체가 사라지게 되었겠죠?

구현 전 클래스의 역할에 대해서 명확히 정의를 내리는 것이 좋을 것 같다고 말씀드리는 거였습니다~

2022-12-20 06:07 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
아하 알겠습니다..
다시 한번 Token Resolver 객체에 대해서 고민해보고, 코드 변경하도록 하겠습니다.

2022-12-21 12:15 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +public class TokenResolver {
`@NoArgsConstructor` 잘못 입력하여 제거 해주었습니니다.

2022-12-21 12:16 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +public class TokenResolver {
그리고 `@Component` 로 빈 등록을 해두고, TokenResolver를 사용하는 곳에서는 다 생성자 주입 방식으로 사용할 수 있도록 변경해주겠습니다.

2022-12-21 14:36 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
리뷰 해 주신 부분에 대해서 질문드립니다.
 > tokenResolver.createToken()은 사실상 예외 발생 로직이 존재하지 않죠?

 라고 생각하신 이유가 있을까요???

예시로 들어주신 두가지 경우가 명확히 error가 발생할 수 있는 상황이라면 
` assertThatCode(() -> new User("name", 1L)).doesNotThrowAnyException(); ` 같은 경우는 생성자에서 유효성 검사에 대한 error 
` assertThatCode(() -> password.checkPassword("password")).doesNotThrowAnyException(); `같은 경우는 checkPassword 라는 메서드에서 패스워드 검증 시 error 가 발생 하는 상황일 것 이라고 생각했습니다.

그런데 생각해보면 createToken 또한 토큰을 생성하는 과정에서 error가 발생할 수 있지 않을까요?

 
 우선, 제가 작성한 테스트 코드가 명확하게 작성 되지 않은 부분에 대해 인지 했습니다.
따라서 다음 두가지를 확인 할 수 있는 코드로 변경하도록 하겠습니다.
- 반환되는 타입이 무엇인지 불명확하기 때문에 어떤 타입의 토큰이 생성되는지 확인
- 반환값에 대해 null이나 empty에 대한 확인

2022-12-21 14:46 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
아 다시 생각해보니까,,, 
> tokenResolver.createToken()은 사실상 예외 발생 로직이 존재하지 않죠? 
라고 말씀하신 의미는 구현 코드 자체에서 예외가 발생 할 수 없으니까 위처럼 말씀해주신걸까요..?
만약 그렇다면 제가 작성했던 테스트 코드는 의미 없는 코드겠네요..

2022-12-21 15:09 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +        Key invalidKey = new SecretKeySpec(invalidSecretKeyBytes, SignatureAlgorithm.HS256.getJcaName());
반영 하도록 하겠습니다. 테스트 코드 작성 해두고 구현 시 놓쳤습니다..

2022-12-21 15:15 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
> 그런데 생각해보면 createToken 또한 토큰을 생성하는 과정에서 error가 발생할 수 있지 않을까? 라는 생각도 들었습니다.

error가 발생할 수 있지 않을까라고 생각이 들었다면 `compact()` 메소드 들어가서 로직 하나씩 보면서 에러 터지는 지 확인해보면 명확히 답변이 나올 수 있는 부분이었다고 생각해요~ 
그리고 error 발생할것이라고 생각했으면 doesNotThrowAnyException() 반대의 createToken() 호출 시에 대한 모든 예외 테스트 코드도 작성해야했는데 그 부분도 작성해주지 않았구요. 해당 예외 테스트 케이스를 작성해주셨다면 코멘트를 드리지 않았을 것 같아요~

사실, compact() 내부에서 예외 발생 로직 조금 있습니다. 근데 확인해보면 지환님께서 작성해주신 로직에서는 발생하지 않을 것으로 보여요~
그리고 말씀하신대로 구현 코드 자체에서 예외가 발생 할 수 없는 점도 내포하여 위와 같이 코멘트 드렸습니다~

2022-12-21 15:21 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    }
자세히 말씀해주셔서 감사합니다!
테스트 코드 작성 시, 더 주의하도록 하겠습니다..!

2022-12-21 15:47 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/config/WebConfig.java
> +}
변경하였습니다..!

2022-12-21 15:48 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +        when(userService.login(any(LoginRequest.class))).thenReturn(loginServiceResponseDto);
저는 가독성이 그렇게 떨어진다고 생각되지는 않았습니다. 
한줄안에서 리턴 값 까지 읽을 수 있는게 통일성이 더 있고, 가독성이 좋다고 생각했습니다.

2022-12-21 16:01 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- `LoginCheckInterceptor` 적용에 따른 변경
    - 줌을 통해 리뷰받은 예외처리 부분 변경 
- `TokenResolver` 를 스프링 빈으로 관리
    -  `Token` 생성 시 ,시크릿 키를 바이트 단위로 변경 후 생성하도록 변경 
- 전체적인 코드 통일성에 따른 변경
    - 생성자를 롬복 방식[ `@RequiredArgsConstrutor`] 으로 변경
- 중복된 DTO 제거
- 테스트 코드 변경
   
## 그 외
- 시크릿 키 관리하는 yml 설정은 애매한 부분이 있어 더 찾아보려고, 리뷰 반영을 아직 못하였습니다. 
 

## 질문 사항
- LoginCheckInterceptor 코드에서 Redirect 로직을 작성을 해두었습니다. 현재는 프런트와 상의한 url은  `/signin` 입니다. 근데 아직 어떤 포트를 쓸지 모르고, 배포 상황에서도 `localhost` 를 사용하는지는 모르겠으나..
일단 리다이렉트 경로를 `localhost:8080/signin` 로 적어두었습니다

2022-12-21 16:02 UTC, ch0ijihwan commented on src/test/java/hamkke/board/controller/UserControllerTest.java
> +    private static final String AUTHORIZATION_HTTP_HEADER = "authorization";
반영하였습니다!

2022-12-23 16:50 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- jwt 관련 변경
   - 시크릿키를 yml 파일로 관리하도록 함
   - 구현 코드에서 key 생성 시, String 타입으로 생성하는 것이 아닌 byte 로 키를 생성하도록 변경하였습니다.
 
 

## 질문 사항
- 없음

2022-12-27 12:25 UTC, seongbeenkim approved these changes
변경사항 확인했으며 질문사항 답변 코멘트에 남겼습니다~

2022-12-27 12:25 UTC, seongbeenkim commented on src/main/java/hamkke/board/web/interceptor/LoginCheckInterceptor.java
> +            response.sendRedirect("localhost:8080/signin");
배포 상황 상관없이 localhost:8080은 빼셔도 됩니다~

2022-12-27 12:25 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    void validateTokenWhenIllegalArgument(final String illegalArgument) {
@DisplayName을 null 또는 빈 문자열일 경우 ~ 와 같이 더 명확하게 작성해주는게 좋을 것 같아요

2022-12-27 13:22 UTC, ch0ijihwan commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
제가 이전에는 ` implementation "io.jsonwebtoken:jjwt:0.9.1" ` 형태로 선언을 해주었습니다. 
그후로 이것 관련해서 더 찾아보기 위해서 ` implementation "io.jsonwebtoken:jjwt:0.9.1" ` 주입 시 어떤 라이브러리가 들어가는지 확인하였고 해당 깃 [주소](https://github.com/jwtk/jjwt) 를 읽어보았습니다.
그런데 [설명](https://github.com/jwtk/jjwt#install-jdk-gradle) 을 보면 의존성 주입을 위와같이 3개로 하여서 한다고 명시되어있어서 변경 하였습니다. 이 부분이 좀 더 구체적으로 어떤 라이브러리를 가져와서 쓰는지 명시하는 것 같아서 변경해주었습니다.

2022-12-27 13:35 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +                         final @Value("${jwt.token-validity-in-seconds}") long tokenValidityInSeconds) {
우선 리뷰를 받기 위해서 `application-jwt.yml` 를 push 하여 올렸습니다. 그러다 보니 git에 올라와있어서 보안이 안지켜지게 되었는데
`application-jwt.yml` 같은 보안적으로 중요한 파일을 git 레포에서 외부인이 확인 못하도록 하는 방법이 있을까요..?
오늘 계속 찾아보았는데, 명확한 해결책이 안나와서 고민입니다.

2022-12-27 13:54 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    void validateTokenWhenIllegalArgument(final String illegalArgument) {
변경하였습니다.

2022-12-27 13:55 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/TokenResolverTest.java
> +    void validateTokenWhenIllegalArgument(final String illegalArgument) {
변경하였습니다

2022-12-28 14:50 UTC, seongbeenkim commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +                         final @Value("${jwt.token-validity-in-seconds}") long tokenValidityInSeconds) {
가장 간단한 방법으로 떠오르는 건 배포 환경별로 jenkins 환경변수 설정에 jwt secret키 넣어주고 
스프링에서 해당 변수 받아오는 방식으로도 갈져갈 수 있을 것 같아요~

2022-12-28 15:12 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +                         final @Value("${jwt.token-validity-in-seconds}") long tokenValidityInSeconds) {
아 이방법을 생각 못했었네요..! 반영해보겠습니다.

2022-12-31 17:58 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- jwt 관련 변경
   - `refresh 토큰` 전략 추가
     - 토큰 재발급 요청 시 `refresh 토큰` 도 재발급하여 보안을 계속 유지하도록 하였습니다.
   - 인증 처리를 위한 `controller` , `service` , `repositroy` 분리

## 질문 사항

- 하나의 헤더의 두가지의 토큰을 넣어주는 것에 대해서 어떻게 생각하시는지 여쭤보고 싶습니다.
    - 처음 구현 했을 때는, `access token header` 와 `refresh token`  커스텀 헤더에  각각 토큰 값을 넣어줬습니다. 하지만 커스텀 헤더 사용을 지양하라는 소나린트에 걸려서 변경을 하였습니다. 
    - 따라서 현재 로직은 하나의 헤더 `Authorization`에 `access token` 과 `refresh token` 을 넣어주었습니다.
  
### 그 외
-  Refresh 토큰 적용(jpa 사용 및 서비스 분리)이 생각보다 어려워서 시간이 걸렸습니다.

2023-01-04 16:59 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- Refresh Token 관련 변경
    - Refresh Token 과 User 의 연관관계 매핑 수정

## 질문 사항
- 지난 시간에 `@OneToOne` 관계를 굳이 사용하지 않아도 된다고 말씀해 주셔서, 변경하였습니다. 
사실 그때 매끄럽게 이해가 되지 않아서, 제대로 변경 했는지 궁금합니다..

피드백 해주셨던 처럼 굳이 사용하지 않는 연관관계를 제거하기 위해서 `user` 객체와 연관 관계를 걸어주지 않고, `Refresh Token` 에서 어떤 유저에 대한 것인지 확인 할수 있는 `LoginId` 를 갖고 있도록 하였습니다. [ `Long` 타입인 `userID` 를 사용하기 보단, 서비스적으로 `User`의 식별을 `LoginId` 로 통일하는게 좋다고 생각해서 `LoginId` 를 사용했습니다.

이후 `Refresh Token` 객체에서 `user` 에 접근 할때 `LoginId` 를 통해 접근 할 수 있도록 변경하였습니다.

용을 지양하라는 소나린트에 걸려서 변경을 하였습니다. 
    - 따라서 현재 로직은 하나의 헤더 `Authorization`에 `access token` 과 `refresh token` 을 넣어주었습니다.
  
### 그 외
-  지난 시간에 새롭게 생성 한 `Refresh Token` 을 업데이트 할 때, 생성된 `Refresh Token` 에 대한 유효검사가 있는게 좋다고 해주셔서 변경을 하였습니다. 우선 UUID로 생성하기 때문에 토큰의 형태를 검사할 수 없다고 생각했고, 따라서 입력 값이 empty 인지 검사하는 로직을 추가하였습니다.

2023-01-07 11:22 UTC, seongbeenkim requested changes
@OneToOne 양방향 연관관계는 잘 제거해주셨네요~
저번에 말씀드린것처럼 `User` 객체에는 `RefereshToken`을 어느 곳에서도 사용하지 않을 것이기 때문에 연관관계를 가질필요가 없고,
`RefreshToken`에서는 어떤 `User`의 대한 토큰인지에 대한 식별만 하는 용도의 정보만 필요하기 때문에, `User`의 unique한 식별자만 가지고 있어도 충분하고 이에 따라서 `User` 객체에 대한 의존성을 가질 필요가 없어도 됩니다.

그리고
`JwtToken`은 `UserId`을 담고 있고, `RefreshToken`은 `LoginId`를 담고 있는 것으로 확인되는데 
두 토큰 모두 한 명의 유저에 대한 토큰의 개념으로 봤을 때 통일성있게 동일한 1개의 정보를 가져가는 게 좋을 것 같아서 이에 관련한 부분 질문남겼으니 확인해주세용~

2023-01-07 11:22 UTC, seongbeenkim commented on src/main/java/hamkke/board/service/AuthenticationService.java
> +        return newRefreshToken;
JwtToken 생성에는 `user.getId()` 를 사용하는데, 
refreshToken 생성에는 `user.getId()`가 아니라 `user.getLoginId()` 로 가져가시는 이유가 궁금해요!

그리고 `switchNewRefreshToken()` 함수가 `newRefreshToken`를 리턴해주시는 이유는 `JwtTokenResponse` 생성을 위해서 하시는 것 같은데
```
String newRefreshToken = UUID.randomUUID().toString();
refreshToken.switchToken(newRefreshToken,LocalDateTime.now());
```
함수로 추출하지 말고 위의처럼 그대로 사용하는것이 더 코드 흐름을 파악하기도 좋고 흐름상 좋을 것 같다는 생각이 들어요.

2023-01-07 11:22 UTC, seongbeenkim commented on src/main/java/hamkke/board/web/jwt/RefreshToken.java
>          token = newToken;
함수의 파라미터로 받아온 newToken이 empty + 기존 토큰과 동일한지에 대한 validation도 있으면 좋을 것 같아요!

2023-01-07 11:22 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/RefreshTokenTest.java
> +        refreshToken.switchToken(newToken, LocalDateTime.now().minusSeconds(1));
아래 테스트 코드에서 `expirationTime.plusSeconds(1);` 해주신 것처럼
기존 `LocalDateTime.now()`가 아닌 `expirationTime`를 활용하셔서 테스트 코드를 작성해주시면 좋을 것 같아요.

시간 관련된 테스트 코드 작성시에는 테스트에 필요한 기준되는 시간을 명확히 지정 후 
테스트 하는 방향에 따라 해당 기준 시간에 맞춰서 작성하게 하는것이 좋습니다~

2023-01-08 08:36 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/RefreshToken.java
> +        }
이부분 나중에 제거해주었습니다. 토큰이 바로 UUID로 생성되어 나오기 때문에 null 이나 empty 인 상황이 없다고 생각했습니다.
리뷰해주신 기존과 동일한 토큰인 경우는 정말희박하게 있을 수 있으니, 해당 부분만 반영해도 괜찮을까요?

2023-01-09 05:47 UTC, ch0ijihwan commented on src/main/java/hamkke/board/service/AuthenticationService.java
> +        return newRefreshToken;
우선 user.getId 를 해준이유는 토큰 적용전에 유저의 식별자를 관리하는것을 user 의 id 로 관리하는게 좋다고 생각했습니다.
하지만 토큰을 적용하면서 LoginId로 관리하기로 한 이상, 해당 부분 변경을 하도록 하겠습니다. 따라서 LoginId로 유저의 식별을 하도록 변경 하겠습니다.

그리고 메서드리팩토링에 관해서는 reissue 라는 메서드 내부로직을 표현하는 코드가 너무 길어서 읽기가 어려울 수도 있겠다고 생각해서 메서드를 분리하였습니다.
가독성을 높힐려고 메서드를 분리해봤는데, 가독성이 더 해치게 되었네요... 리뷰내용 반영하도록 하겠습니다.

2023-01-09 05:49 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/RefreshTokenTest.java
> +        refreshToken.switchToken(newToken, LocalDateTime.now().minusSeconds(1));
혹시 
> 테스트에 필요한 기준되는 시간을 명확히 지정 후

이에 대한 말씀은 now() 를 쓰는 것 또한 명확한 시간이 아니라는 말씀이신가요?

2023-01-09 07:04 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/RefreshTokenTest.java
> +        refreshToken.switchToken(newToken, LocalDateTime.now().minusSeconds(1));
`now()` 를 사용하면 테스트를 할 때마다 입력되는 토큰 만료시간이 바뀌기 때문에, 테스트하기 좋지 않은 것으로 생각되어서
지정된 시간을 기준으로 테스트 할 수 있도록 변경하였습니다.
무엇보다 테스트 돌리는 환경에 따라서 `now()` 의 값이 다르기 때문에 좋지 않다고 생각했습니다.

2023-01-09 07:14 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
- Refresh Token 관련 변경
    - 페이로드 내부 값을 userId를 들고 있던 것을 Logind 로변경

## 질문 사항
- 현재 pr 말고 회원가입 부분에서 회원가입이 완료되면 user.id 를 반환하는 로직을 만들어두었습니다. 
토큰 기능을 만들면서 user의 식별을 Logind 해주기로 했으니, 이것도 변경을 해야한다고 생각하는데, 현재 브랜치에서 변경하는 것 보다
회원가입 브랜치에서 해당 로직을 변경해줘야한다고 생각했습니다.
하지만 회원가입 브랜치 이후로 파생된 브랜치들이 있어서, 어디서 변경을 해줘야 깃을 제대로 활용하여 효율적으로 변경하는지 고민입니다.

제가 생각 했을 때는 회원가입 기능 구현 브랜치로 체크아웃해서 변경을 하고, 이후 차례대로 파생된 브랜치들(로그인 기능 구현, jwt 기능 구현)에서  변경된 브랜치(회원가입 브랜치)를 merge 하여 충돌을 잡는게 올바르다고 생각하는데, 이렇게 변경을 해도 괜찮을 까요?

  
### 그 외
-  없음

2023-01-09 09:10 UTC, seongbeenkim commented on src/test/java/hamkke/board/web/jwt/RefreshTokenTest.java
> +        refreshToken.switchToken(newToken, LocalDateTime.now().minusSeconds(1));
[테스트 코드에선 LocalDate.now()를 쓰지말자.](https://jojoldu.tistory.com/416) 내용에서와 같이 테스트가 항상 같은 결과를 만들어야 하는 관점에서, 테스트 코드에 필요한 시간들은 특정 값으로 지정해두고 사용하는 것이 안전하다고 생각해요~

2023-01-09 10:23 UTC, seongbeenkim approved these changes
넵넵 회원가입 기능 구현 수정 -> 로그인 기능 구현 merge -> jwt 기능 구현 merge 순으로 해주면 좋을 것 같네요~

2023-01-10 06:06 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/RefreshToken.java
> +
처음에는 새롭게 들어온 토큰 값은 리프레시 토큰으로서 사용됨에 문제가 없어 입력에 대한 문제가 아니라고 생각했습니다. 또한  내부의 리프레시 토큰이 이미 존재하는 상태라고 생각해서 `IllegalStateException` 이라고 생각했습니다. 그런데 다시 생각해보니 결국 입력이 잘못된 것이라서 `IllegalArgumentException` 이 맞는 것 같습니다. 변경하도록 하겠습니다.

2023-01-10 06:13 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/RefreshToken.java
> +        }
넵 구체적인 상황을 명시하도록 변경하겠습니다

2023-01-11 06:30 UTC, ch0ijihwan commented on src/test/java/hamkke/board/web/jwt/RefreshTokenTest.java
> +        refreshToken.switchToken(newToken, LocalDateTime.now().minusSeconds(1));
글만 읽고 코멘트를 못남겼었습니다..!

내용 확인하고, 명확한 시간을 쓰도록 변경하였습니다.

2023-01-12 13:48 UTC, ch0ijihwan commented
# 회원 로그인 로직 생성
### 이슈 번호 : #25 - #38
## 변경 사항 
-  `ExceptionHandler` 에서 예외를 못잡는 부분 변경

## 질문 사항
- 없음

  
### 그 외
- 없음

2023-01-13 15:56 UTC, seonghun127 commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +                         final @Value("${jwt.token-validity-in-seconds}") long tokenValidityInSeconds) {
지환님~ jenkins 환경변수로 추출하는 작업하셨나요? (아래 커밋 내역들 보는데 잘 못찾겠어서...)

혹시 안돼있다면 이 작업은 issue를 새로 따고 거기서 진행하는건 어떨까요?

말씀드리는 배경은, 이 PR 내용이 너무 길어져서 하나의 PR에 작업 범위가 너무 커지는게 우려돼서입니다.

현업에서도 브랜치의 작업 볼륨을 최대한 작게 가져가려고 노력해요. 그 이유는 애자일과 관련이 있는데요~
최대한 빠르게 개발 -> 코드 리뷰 -> 배포 -> 테스트 과정을 가져가기 위함이에요.
그외 이유론 작업한 내용을 쉽게 찾기 위함인데, 티켓 안에 다양한 내용이 있는 것보다 하나의 티켓이 하나의 작업만 하는게 나중에 '이 작업을 어디서 했었지?' 라고 찾을 때 쉬워요!

2023-01-13 16:02 UTC, seonghun127 commented on src/main/java/hamkke/board/web/jwt/RefreshToken.java
> +
불필요한 개행이 들어갔네요~

2023-01-13 16:08 UTC, seonghun127 approved these changes
코드가 깰꼼하네요 :)

2023-01-13 16:09 UTC, ch0ijihwan commented
감사합니다!

2023-01-13 16:15 UTC, merged

2023-01-13 16:41 UTC, ch0ijihwan commented on src/main/java/hamkke/board/web/jwt/TokenResolver.java
> +                         final @Value("${jwt.token-validity-in-seconds}") long tokenValidityInSeconds) {
아직 작업 하지 않았습니다. 이슈 티켓만들어두겠습니다!